apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kn-es-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/enable-cors: "true"
    {{- if .Values.global.tlssecret }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    nginx.ingress.kubernetes.io/server-snippet: |
        add_header Allow "GET, POST, HEAD" always;
        if ( $request_method !~ ^(GET|POST|HEAD|OPTIONS)$ ) {
            return 405;
        }
        location ~ ^/(?!(datasets38|datasets30|regions22|regions17|datasets32|regions21)) {
           return 405;
        }
        location ~ ^/(datasets38|datasets30|regions22|regions17|datasets32|regions21)/(?!(_search|_mapping)) {
           return 405;
        }
        location ~ ^/_cat/(?!indices) {
           return 405;
        }
spec:
  rules:
    - host: {{ .Values.global.externalUrlEs }}
      http:
        paths:
        - path: /
          backend:
            serviceName: elasticsearch
            servicePort: 9200
  {{- if .Values.global.tlssecret }}
  tls:
   - secretName: {{ .Values.global.tlssecret }}
     hosts:
     - {{ .Values.global.externalUrlEs }}
  {{- end }}
