{{- if .Values.includeInitialJobs }}
{{- range .Values.config }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: connector-{{ .id }}
{{ $params := dict "root" $ "jobConfig" . }}
{{ template "magda.connectorJobSpec" $params }}
...
{{- end }}
{{- end }}