apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.global.tlssecret }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
  generation: 2
  name: kn-ingress
spec:
  rules:
  - host: {{ .Values.global.externalUrlkn }}
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 80
        path: /
  {{- if .Values.global.tlssecret }}
  tls:
  - secretName: {{ .Values.global.tlssecret }}
    hosts:
    - {{ .Values.global.externalUrlkn }}
  {{- end }}
